import React, { useState } from 'react';
import ValidationErrors from '@/components/ValidationErrors';
import { Head, setLayoutProps, useForm } from '@/util/Inertia';
import { Button, FloatingLabel, Form } from 'react-bootstrap';

export default function TwoFactorChallenge() {
    const [useRecoveryCode, setUseRecoveryCode] = useState(false);
    const { data, setData, post, processing, errors } = useForm({
        code: "",
        recovery_code: "",
    });

    const onHandleChange = (event) => {
        setData(event.target.name, event.target.value);
    };

    const toggleRecoveryCode = () => {
        setUseRecoveryCode((value) => !value);
        setData({ code: "", recovery_code: "" });
    };

    const submit = (e) => {
        e.preventDefault();

        post(route("two-factor.login"));
    };

    setLayoutProps({
        title: "Two-Factor Verification",
        description: useRecoveryCode
            ? "Enter one of your emergency recovery codes."
            : "Enter the code generated by your authenticator app.",
    });

    return (
        <>
            <Head title="Two-Factor Verification" />
            <div className="">
                <ValidationErrors errors={errors} />
                <form className="margin-bottom-0" onSubmit={submit}>
                    {useRecoveryCode ? (
                        <FloatingLabel controlId="recovery_code" label="Recovery Code" className="mb-3">
                            <Form.Control
                                name="recovery_code"
                                placeholder="recovery code"
                                value={data.recovery_code}
                                className="form-control form-control-lg"
                                autoComplete="one-time-code"
                                autoFocus
                                onChange={onHandleChange}
                            />
                        </FloatingLabel>
                    ) : (
                        <FloatingLabel controlId="code" label="Authentication Code" className="mb-3">
                            <Form.Control
                                name="code"
                                placeholder="code"
                                value={data.code}
                                className="form-control form-control-lg"
                                inputMode="numeric"
                                autoComplete="one-time-code"
                                autoFocus
                                onChange={onHandleChange}
                            />
                        </FloatingLabel>
                    )}
                    <Form.Group className="mb-3">
                        <div className="d-grid gap-2">
                            <Button type={"submit"} size={"lg"} variant={"primary"} disabled={processing} block>
                                Verify
                            </Button>
                        </div>
                    </Form.Group>
                </form>
                <div className="text-center">
                    <Button variant="link" onClick={toggleRecoveryCode}>
                        {useRecoveryCode ? "Use an authentication code instead" : "Use a recovery code instead"}
                    </Button>
                </div>
            </div>
        </>
    );
}
